version: 2.1

commands:
  setup-linux-packages:
    steps:
      - run:
        name: "Installing base packages"
        command: |
          apt update
          apt install -y cmake libvulkan-dev

jobs:
  linux:
    executor: ubuntu-16_04
    steps:
      - checkout
      - setup-linux-packages
      - run:
        name: Create build directory
        command: mkdir -p build
        
      - run:
        name: Setup cmake
        command: |
          cd build
          cmake ..

workflows:
  build-workflow:
    jobs:
      - build
