version: 2.1

jobs:
  build-linux:
    docker:
      - image: cimg/base:2022.01
      
    steps:
      - checkout

      - run:
          name: Install CMake
          command: sudo apt update && sudo apt install -y cmake

      - run:
          name: Install Vulkan
          command: sudo apt-get update && sudo apt-get install -y libvulkan-dev

      - run:
          name: Setup GCC 11
          command: |
            sudo apt install -y gcc-11 g++-11
            echo 'export CC=gcc-11' >> $BASH_ENV
            echo 'export CXX=g++-11' >> $BASH_ENV

      - run:
          name: Setup CMake
          command: cmake -Bbuild

      - run:
          name: Start Build
          command: cmake --build build

workflows:
  build-workflow:
    jobs:
      - build-linux
