version: 2.1

jobs:
  build-linux:
    docker:
      - image: cimg/base:2022.01 # Base Ubuntu image

    steps:
      - checkout

      - run:
          name: Install CMake
          command: |
          sudo apt update
          sudo apt install -y cmake

      - run:
          name: Install Vulkan
          command: |
          sudo apt-get update
          sudo apt-get install -y libvulkan-dev

      - run:
          name: Setup GCC 11
          command: |
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo apt install -y gcc-11 g++-11
            echo 'export CC=gcc-11' >> $BASH_ENV
            echo 'export CXX=g++-11' >> $BASH_ENV

      - run:
          name: Setup Build Files
          command: cmake -BBuild

      - run:
          name: Start Build
          command: cmake --build Build

workflows:
  build-workflow:
    jobs:
      - build-linux
