version: 2.1

jobs:
  build-linux:
    docker:
      - image: cimg/base:2022.01
    steps:
      - checkout

      # Install base packages : CMake, Vulkan
      - run:
          name: Install base packages
          command: |
            apt update
            apt install -y cmake libvulkan-dev
            
      # Use GCC 11
      - run:
          name: Setup compiler
          command: |
            apt install -y g++-11
            echo 'export CC=gcc-11' >> $BASH_ENV
            echo 'export CXX=g++-11' >> $BASH_ENV

      - run:
          name: Create build directory
          command: mkdir -p build
        
      - run:
          name: Setup CMake
          command: |
            cd build
            cmake ..

      - run:
          name: Make
          command: |
            make

workflows:
  build-workflow:
    jobs:
      - build-linux
